export type MenuItem = { name: string; price: string | number };
export type MenuCategory = { category: string; items: MenuItem[] };

export const menu: MenuCategory[] = [
  {
    category: "Soups",
    items: [
      { name: "Cream of tomato soup", price: 90 },
      { name: "veg hot & sour soup", price: 90 },
      { name: "veg manchow soup", price: 90 },
      { name: "chicken hot & sour soup", price: 110 },
      { name: "chicken sweet corn soup", price: 110 },
      { name: "chicken manchow soup", price: 110 },
    ],
  },
  {
    category: "Indian Bread's",
    items: [
      { name: "butter tandoori roti", price: 35 },
      { name: "butter naan", price: 40 },
      { name: "garlic naan", price: 40 },
      { name: "pudina naan", price: 40 },
      { name: "panneer naan", price: 65 },
      { name: "arabian nawaabi kulcha", price: 75 },
    ],
  },
  {
    category: "Chinese",
    items: [
      { name: "zeera rice", price: 220 },
      { name: "butter rice", price: 220 },
      { name: "veg fried rice", price: 230 },
      { name: "egg fried rice", price: 230 },
      { name: "mushroom fried rice", price: 240 },
      { name: "kaju rice", price: 260 },
      { name: "chicken fried rice", price: 260 },
      { name: "paneer fried rice", price: 260 },
      { name: "schezwan chicken fried rice", price: 270 },
      { name: "arab street special fried rice", price: 280 },
      { name: "prawns fried rice", price: 290 },
      { name: "sea food fried rice", price: 290 },
    ],
  },
  {
    category: "Sea Food",
    items: [
      { name: "apollo fish", price: 320 },
      { name: "fish majestic", price: 320 },
      { name: "fish 65", price: 320 },
      { name: "garlic chilli fish", price: 320 },
      { name: "galic butter fish", price: 320 },
      { name: "fish fingers", price: 320 },
      { name: "prawns garlic", price: 320 },
      { name: "chilli prawns", price: 320 },
      { name: "garlic prawns", price: 320 },
      { name: "loose prawns", price: 320 },
      { name: "fish fingers", price: 330 },
      { name: "arabic saute prawns", price: 330 },
    ],
  },
  {
    category: "Kebabs",
    items: [
      { name: "chicken lollipop [4pcs]", price: 230 },
      { name: "chicken wings [4pcs]", price: 230 },
      { name: "chicken bbq [3pcs]", price: 280 },
      { name: "panneer kebab", price: 280 },
      { name: "kalmi kebab", price: 280 },
      { name: "murgh banjara kebab", price: 290 },
      { name: "rashmi kebab", price: 290 },
      { name: "samurai kebab", price: 290 },
      { name: "kasturi kebab (3pcs)", price: 290 },
      { name: "garlic kebab", price: 290 },
      { name: "murgh malai kebab", price: 290 },
      { name: "haryali tikka", price: 290 },
      { name: "chicken seekh kebab", price: 299 },
      { name: "tandoori chicken [half/full]", price: "280 / 550" },
      { name: "tandoori platter", price: 480 },
    ],
  },
  {
    category: "Appetizer",
    items: [
      { name: "crispy veg", price: 240 },
      { name: "crispy chilli potato", price: 240 },
      { name: "babycorn 65", price: 250 },
      { name: "babycorn manchuriya", price: 250 },
      { name: "chilli babycorn", price: 250 },
      { name: "crispy babycorn", price: 250 },
      { name: "mushroom 65", price: 250 },
      { name: "chilli mushroom", price: 250 },
      { name: "mushroom manchuriya", price: 250 },
      { name: "paneer manchuriya", price: 250 },
      { name: "paneer 65", price: 280 },
      { name: "paneer 555", price: 280 },
      { name: "ginger paneer", price: 260 },
      { name: "paneer chilli", price: 280 },
      { name: "paneer majestic", price: 300 },
      { name: "chicken drumsticks", price: 230 },
      { name: "chicken crispy fried chicken", price: 300 },
      { name: "ginger chicken", price: 300 },
      { name: "chicken sticks", price: 300 },
      { name: "hongkong chicken", price: 300 },
      { name: "chicken 65", price: 300 },
      { name: "chicken 555", price: 300 },
      { name: "chicken capsicum", price: 300 },
      { name: "chicken majestic", price: 300 },
      { name: "pepper chicken", price: 300 },
      { name: "cashewnut chicken", price: 300 },
      { name: "dragon chicken", price: 300 },
      { name: "honey sesame chilli chicken", price: 300 },
      { name: "schezwan chicken", price: 300 },
      { name: "crispy chicken", price: 320 },
      { name: "basket chicken", price: 320 },
      { name: "classic lemon chicken", price: 320 },
      { name: "chicken patiyala", price: 320 },
    ],
  },
  {
    category: "Main Course",
    items: [
      { name: "methi chaman", price: 250 },
      { name: "mushroom masala", price: 250 },
      { name: "kaju panner", price: 270 },
      { name: "tomoto cashew curry", price: 270 },
      { name: "paneer tikka masala", price: 280 },
      { name: "paner butter masala", price: 280 },
      { name: "kadai paneer", price: 280 },
      { name: "dum ka chicken", price: 270 },
      { name: "andhra chicken", price: 290 },
      { name: "telengana chicken", price: 290 },
      { name: "chicken kala mirch", price: 290 },
      { name: "chicken maharani", price: 290 },
      { name: "chicken chettinadu", price: 290 },
      { name: "kolhapuri chicken", price: 290 },
      { name: "punjabi chicken", price: 290 },
      { name: "chicken tikka masala", price: 300 },
      { name: "chicken chatpata (b/l)", price: 300 },
      { name: "arab street special boneless", price: 300 },
      { name: "aachari chicken (b/l)", price: 300 },
      { name: "kadai chicken", price: 300 },
      { name: "butter chicken masala", price: 300 },
      { name: "chicken mughlai", price: 300 },
      { name: "murgh mussalam", price: 310 },
      { name: "afghani chicken", price: 320 },
      { name: "kadai mutton", price: 350 },
      { name: "mutton afghani", price: 350 },
      { name: "andhra mutton", price: 350 },
      { name: "punjabi mutton", price: 350 },
      { name: "mutton masala", price: 350 },
      { name: "andhra fish curry", price: 330 },
      { name: "jumbo prawns curry", price: 350 },
    ],
  },
  {
    category: "Biriyani's",
    items: [
      { name: "dawood dum biryani", price: 229 },
      { name: "paneer makhni biryani", price: 280 },
      { name: "mushroom biryani", price: 280 },
      { name: "cashew biryani", price: 320 },
      { name: "panner tikka biryani", price: 320 },
      { name: "chicken wings/lollipop biryani", price: 320 },
      { name: "chicken fry piece biryani", price: 320 },
      { name: "chicken curry biryani", price: 330 },
      { name: "special chicken biryani", price: 330 },
      { name: "chicken tikka biryani", price: 350 },
      { name: "chicken mughalai biryani", price: 350 },
      { name: "arab street milav biryani", price: 340 },
      { name: "tangdi biryani", price: 370 },
      { name: "tandoori biryani", price: 370 },
      { name: "bbq biryani", price: 370 },
      { name: "mutton dum biryani", price: 380 },
      { name: "spicy fish biryani", price: 380 },
      { name: "prawns biryani", price: 380 },
      { name: "mutton curry biryani", price: 400 },
      { name: "gongura mutton biryani", price: 400 },
    ],
  },
  {
    category: "Arab Street Thali's",
    items: [
      { name: "chicken dum thali half", price: 500 },
      { name: "chicken wings/lollipop thali half", price: 630 },
      { name: "chicken fry piece thali half", price: 630 },
      { name: "BBQ / Tangdi / Tandoori thali half", price: 660 },
      { name: "mutton dum thali half", price: 770 },
      { name: "mutton curry thali half", price: 790 },
      { name: "arab street kumbhakarna thali half", price: 790 },
      { name: "chicken dum thali full", price: 800 },
      { name: "chicken tandoori/tangdi/bbq full", price: 950 },
      { name: "chicken wings/lollipop full", price: 930 },
      { name: "chicken fry piece full", price: 930 },
      { name: "mutton dum thali full", price: 1110 },
      { name: "mutton curry thali full", price: 1160 },
      { name: "arab street kumbhakarna thali full", price: 1390 },
    ],
  },
  {
    category: "+ Add‑Ons",
    items: [
      { name: "EXTRA RICE--FULLY COOKED BASMATI BIRYANI RICE", price: 129 },
      { name: "EXTRA PIECE", price: 109 },
    ],
  },
  {
    category: "Drinks",
    items: [
      { name: "MINERAL WATER BOTTLE", price: 20 },
      { name: "COOL DRINK", price: 25 },
    ],
  },
];

export const NAV_LINKS = [
  {
    name: "Home",
    href: "",
  },
  {
    name: "About",
    href: "menu",
  },
  {
    name: "Menu",
    href: "menu",
  },
  {
    name: "About",
    href: "about",
  },
  {
    name: "Location",
    href: "contact",
  },
];